### ISSUE TITLE
Cannot query private notebooks

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-github-issue-notebooks#2]
![image](https://user-images.githubusercontent.com/4674940/78089954-af74e000-737d-11ea-8c8a-ff070814adf5.png)

The resulting query
``` https://api.github.com/search/issues?q=repo%3Amicrosoft%2Fvscode-github-issue-notebooks%20author%3Akieferrm&sort=undefined&order=desc&per_page=100&page=0``` looks ok though.

**Comment by jrieken** [comment]
must be an issue with the access token

**Comment by jrieken** [comment]
@RMacfarlane This might be an interesting scenario for the auth-API, e.g I don't want to always ask for access to private repos as that might turn off people but I wanna explain user what this is for. Maybe we tweak the API towards that so that an explainer shows what you get with approval of what scopes and what you don't get. E.g for this extension it is

* no auth -> everything works but you might be throttled quickly, some features like @me or your-repo-completions don't work
* auth, no scopes -> works, but no private repo search
* auth, [repo]-scope -> everything works but you had to give a power-token

**Comment by jrieken** [comment]
I am now using the `repo`-scope by default. This allows to query private repos but it is big hammer for what we need. Anyways, thats the only thing GH gives us
