### ISSUE TITLE
Show Error/Warning when the query is invalid

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-github-issue-notebooks#24]
Issue Type: <b>Bug</b>

Below query gives me correct results

```
$VERIFICATION -assignee:@me sort asc by created
```

but this one return zero results but shows no error/warning
```
$VERIFICATION sort asc by created -assignee:@me
```

Extension version: 0.0.18
VS Code version: Code - Insiders 1.45.0-insider (a0fe37870c42e0704a492cdc6b8550b4cf23f63c, 2020-04-30T05:36:26.465Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.42GB free)|
|Process Argv|-psn_0_28097226|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
That's a feature 🤓 The `sort asc by created` string is custom to this extension and therefore only used when at the end, otherwise it's just a normal query-string. There is even semantic highlighting for this ;-)

<img width="403" alt="Screenshot 2020-05-20 at 09 43 43" src="https://user-images.githubusercontent.com/1794099/82419242-66d4cb80-9a7e-11ea-8ac9-b6fac3e5ceae.png">

Tho, this has been raised before, I am open for suggestions. I can add an info/hint diagnostic message when this appears
