### ISSUE TITLE
"Unknown label" when repo is in variable

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-github-issue-notebooks#31]
Have one cell with `$REPOS=repo:microsoft/vscode`, and another with `$REPOS label:notebook`. The second cell gets a warning on the label that it's unknown, although I get the correct labels in intellisense.

**Comment by jrieken** [comment]
@roblourens can you try to repro again? I cannot and I believe this was due to missing node cell contents from the core.

**Comment by roblourens** [comment]
Yeah I don't get the error now, but now I don't get suggestions for labels, dunno if that's expected.

**Comment by jrieken** [comment]
So, this works

<img width="392" alt="image" src="https://user-images.githubusercontent.com/1794099/83546271-b5fc1100-a500-11ea-82f7-3c5c7e092ec2.png">

but this doesn't ⬇️ That's because not all repos define the label in question. I'll make sure that the error is more clear and less severe 

<img width="731" alt="image" src="https://user-images.githubusercontent.com/1794099/83546254-b1cff380-a500-11ea-8226-55131fde5e56.png">

**Comment by jrieken** [comment]
This is now just a hint tell you that a milestone or label doesn't for certain repos. It's still a warning when it doesn't exist anywhere

<img width="581" alt="Screenshot 2020-06-03 at 14 23 10" src="https://user-images.githubusercontent.com/1794099/83636149-c31f0b80-a5a5-11ea-93a0-16bf9cb57f62.png">
