### ISSUE TITLE
Pull requests should be rendered with the PR icon and not the issue icon

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-github-issue-notebooks#7]
![image](https://user-images.githubusercontent.com/172399/78296985-f950f800-752e-11ea-954f-5777c467e65d.png)

**Comment by jrieken** [comment]
Icons should also be theme-aware, eg light and dark

**Comment by jrieken** [comment]
<img width="336" alt="Screenshot 2020-04-29 at 16 34 17" src="https://user-images.githubusercontent.com/1794099/80608619-54dfaa00-8a37-11ea-9a0a-5303b13901fa.png">

This is now using the correct PR icon. However,  GH uses colours for open, merged, and closed and we are more in favour icons (I assume). @misolori Do you have an idea? Should I try some colour or should we fiddle with the icons?

**Comment by misolori** [comment]
We have `git-merge` as a codicon:

![image](https://user-images.githubusercontent.com/35271042/80628964-ff8ba480-8a06-11ea-9b41-a81ce5d53757.png)

Given that the GitHub desktop app also shows PRs, they don't use color there:

![image](https://user-images.githubusercontent.com/35271042/80629559-dc152980-8a07-11ea-8512-1c44316caa10.png)

I'd opt for no color since it will be hard to theme. But I do agree that they seem a bit harder to differentiate.
