### ISSUE TITLE
How to authenticate

### ISSUE THREAD

**Issue by cognominal** [microsoft/vscode-github-issue-notebooks#88]
I am a noob in ts and to notebooks but I like this extension. Thx.
Could not figure how to authenticate. I am already authenticated to github within other extensions but I supposed
this is independant.

![auth](https://user-images.githubusercontent.com/16176/112975004-6c497a80-9153-11eb-989d-6e589364faa2.jpg)

**Comment by giggio** [comment]
I'm also interested in this. I'm seeing a different error message:
`HttpError: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}`

I'm doing:

````
$repo=repo:myorg/myrepo
$repo is:open type:issue
````

I see this is related to #2 but I'm not sure how they solved it.

**Comment by giggio** [comment]
I'm also interested in this. I'm seeing a different error message:
`HttpError: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}`

I'm doing:
````
$repo=repo:myorg/myrepo
$repo is:open is:issue
````

I see this is related to #2 but I'm not sure how they solved it.

**Comment by jrieken** [comment]
<img width="1014" alt="Screenshot 2021-04-15 at 09 30 12" src="https://user-images.githubusercontent.com/1794099/114831058-39e38280-9dcd-11eb-8347-8760c9db3ec9.png">

This extension uses the built-in GitHub authentication extension. You should be seeing a prompt at the account icon saying that Github Issue Notebooks wants to use your GH auth

**Comment by giggio** [comment]
It worked! Thanks!
